title = 'Hive Cyrus'
graphicspath = "res/graphics"
tilepath = "tiles"
spritepath = "sprites"
levelpath = 'res/stages/rooms'
lightpath = "light.png"
tilesize = 40
windowwidth = (800/40) - 1
windowheight = (600/40) - 1
