title = 'Hive Cyrus'
graphicspath = "res/graphics"
tilepath = "tiles"
spritepath = "sprites"
levelpath = 'res/stages/rooms'
lightpath = "light2.png"
playerpath = "player"
queenpath = "queen"
dronepath = "drone"
musicpath = 'res/music'
tilesize = 40
windowwidth = (800/40) - 1
windowheight = (600/40) - 1
